/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nuevaaltasql;
import java.awt.Color;
import java.awt.Label;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author Asrie
 */
public class JFRAME_SQL extends javax.swing.JFrame {

    /**
     * Creates new form JFRAME_SQL
     */
    public JFRAME_SQL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreField = new javax.swing.JTextField();
        imgUrlField = new javax.swing.JTextField();
        estadoGrlField = new javax.swing.JTextField();
        dañosField = new javax.swing.JTextField();
        ciudadField = new javax.swing.JTextField();
        calleField = new javax.swing.JTextField();
        coloniaField = new javax.swing.JTextField();
        colorField = new javax.swing.JTextField();
        formaField = new javax.swing.JTextField();
        utilidadField = new javax.swing.JTextField();
        materialField = new javax.swing.JTextField();
        tamañoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Colonia = new javax.swing.JLabel();
        Colonia1 = new javax.swing.JLabel();
        Colonia2 = new javax.swing.JLabel();
        Colonia3 = new javax.swing.JLabel();
        Colonia4 = new javax.swing.JLabel();
        Tamaño = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });

        imgUrlField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgUrlFieldActionPerformed(evt);
            }
        });

        estadoGrlField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoGrlFieldActionPerformed(evt);
            }
        });

        dañosField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dañosFieldActionPerformed(evt);
            }
        });

        ciudadField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadFieldActionPerformed(evt);
            }
        });

        calleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calleFieldActionPerformed(evt);
            }
        });

        coloniaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coloniaFieldActionPerformed(evt);
            }
        });

        colorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorFieldActionPerformed(evt);
            }
        });

        formaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formaFieldActionPerformed(evt);
            }
        });

        utilidadField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilidadFieldActionPerformed(evt);
            }
        });

        materialField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialFieldActionPerformed(evt);
            }
        });

        tamañoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamañoFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Imagen");

        jLabel3.setText("Estado General");

        jLabel4.setText("Daños?");

        jLabel5.setText("Ciudad");

        jLabel6.setText("Calle");

        Colonia.setText("Colonia");

        Colonia1.setText("Color");

        Colonia2.setText("Forma");

        Colonia3.setText("Proposito/Utilidad");

        Colonia4.setText("Material");

        Tamaño.setText("Tamaño");

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addComponent(Colonia4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Colonia1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Colonia2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Colonia3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tamañoField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(materialField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(utilidadField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formaField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coloniaField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calleField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ciudadField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dañosField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estadoGrlField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2)))
                .addContainerGap(384, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ID, calleField, ciudadField, coloniaField, colorField, dañosField, estadoGrlField, formaField, imgUrlField, materialField, nombreField, tamañoField, utilidadField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgUrlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoGrlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dañosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coloniaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Colonia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Colonia1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Colonia2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(utilidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Colonia3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materialField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Colonia4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamañoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tamaño))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void imgUrlFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgUrlFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imgUrlFieldActionPerformed

    private void estadoGrlFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoGrlFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoGrlFieldActionPerformed

    private void dañosFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dañosFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dañosFieldActionPerformed

    private void ciudadFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadFieldActionPerformed

    private void calleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calleFieldActionPerformed

    private void coloniaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coloniaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coloniaFieldActionPerformed

    private void colorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorFieldActionPerformed

    private void formaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formaFieldActionPerformed

    private void utilidadFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilidadFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utilidadFieldActionPerformed

    private void materialFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialFieldActionPerformed

    private void tamañoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamañoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamañoFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        enviar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(ID.getText());
        ConsultaID(id);
    }//GEN-LAST:event_IDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(ID.getText());
        actualizarDatos(id);
    }//GEN-LAST:event_jButton2ActionPerformed
private void ConsultaID(int objetoPerdidoId){
Connection cn = null;
PreparedStatement pst = null;
ResultSet rs = null;
try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    cn = DriverManager.getConnection("jdbc:mysql://localhost/cosasperdidas", "root", "");

    String query = """
        SELECT 
            op.NAME_OP,
            d.COLOR, d.FORMA, d.UTILIDAD, d.MATERIAL, d.TAMAÑO,
            u.CIUDAD, u.CALLE, u.COLONIA,
            e.EST_GRL_STATE, e.DAÑOS,
            op.IMG_OP_URL
        FROM objeto_perdido op
        INNER JOIN descripcion d ON op.ID_DESCRIPCION_OP = d.DESCRIP_ID
        INNER JOIN ubicacion u ON op.ID_LUGAR_OP = u.UBICACION_ID
        INNER JOIN estado e ON op.ID_EST_OP = e.STATE_ID
        WHERE op.ID_OP = ?; 
                   """;

    pst = cn.prepareStatement(query);
    pst.setInt(1, objetoPerdidoId); 
    rs = pst.executeQuery();

    if (rs.next()) {
        String nameOp = rs.getString("NAME_OP");
        String color = rs.getString("COLOR");
        String forma = rs.getString("FORMA");
        String utilidad = rs.getString("UTILIDAD");
        String material = rs.getString("MATERIAL");
        String tamaño = rs.getString("TAMAÑO");

        String ciudad = rs.getString("CIUDAD");
        String calle = rs.getString("CALLE");
        String colonia = rs.getString("COLONIA");

        String estadoGrl = rs.getString("EST_GRL_STATE");
        String daños = rs.getString("DAÑOS");

        String imgUrl = rs.getString("IMG_OP_URL");
        //int userId = rs.getInt("ID_USER_OP");

        // Cambiar por interfaz para ver despues
       nombreField.setText(nameOp);
       colorField.setText(color);
       formaField.setText(forma);
       utilidadField.setText(utilidad);
       materialField.setText(material);
       tamañoField.setText(tamaño);
       ciudadField.setText(ciudad);
       calleField.setText(calle);
       coloniaField.setText(colonia);
       estadoGrlField.setText(estadoGrl);
       dañosField.setText(daños);
       imgUrlField.setText(imgUrl);
        System.out.println(pst);
    } else {
        System.out.println("ID no ligado o existente.");
    }

} catch (Exception e) {
    e.printStackTrace();
} finally {
    try {
        if (rs != null) rs.close();
        if (pst != null) pst.close();
        if (cn != null) cn.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
}

private void actualizarDatos(int objetoPerdidoId) {
    Connection cn = null;
    PreparedStatement pstDescripcion = null;
    PreparedStatement pstUbicacion = null;
    PreparedStatement pstEstado = null;
    PreparedStatement pstObjetoPerdido = null;

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        cn = DriverManager.getConnection("jdbc:mysql://localhost/cosasperdidas", "root", "");
        cn.setAutoCommit(false); // Start transaction

        String color = colorField.getText();
        String forma = formaField.getText();
        String utilidad = utilidadField.getText();
        String material = materialField.getText();
        String tamano = tamañoField.getText();

        String ciudad = ciudadField.getText();
        String calle = calleField.getText();
        String colonia = coloniaField.getText();

        String estadoGrl = estadoGrlField.getText();
        String danos = dañosField.getText();

        String nameOp = nombreField.getText();
        String imgUrl = imgUrlField.getText();

        // Actualizar relacionadas
        String updateDescripcion = "UPDATE descripcion d " +
                                    "INNER JOIN objeto_perdido op ON op.ID_DESCRIPCION_OP = d.DESCRIP_ID " +
                                    "SET d.COLOR = ?, d.FORMA = ?, d.UTILIDAD = ?, d.MATERIAL = ?, d.TAMAÑO = ? " +
                                    "WHERE op.ID_OP = ?";
        pstDescripcion = cn.prepareStatement(updateDescripcion);
        pstDescripcion.setString(1, color);
        pstDescripcion.setString(2, forma);
        pstDescripcion.setString(3, utilidad);
        pstDescripcion.setString(4, material);
        pstDescripcion.setString(5, tamano);
        pstDescripcion.setInt(6, objetoPerdidoId);
        pstDescripcion.executeUpdate();

        String updateUbicacion = "UPDATE ubicacion u " +
                                 "INNER JOIN objeto_perdido op ON op.ID_LUGAR_OP = u.UBICACION_ID " +
                                 "SET u.CIUDAD = ?, u.CALLE = ?, u.COLONIA = ? " +
                                 "WHERE op.ID_OP = ?";
        pstUbicacion = cn.prepareStatement(updateUbicacion);
        pstUbicacion.setString(1, ciudad);
        pstUbicacion.setString(2, calle);
        pstUbicacion.setString(3, colonia);
        pstUbicacion.setInt(4, objetoPerdidoId);
        pstUbicacion.executeUpdate();

        String updateEstado = "UPDATE estado e " +
                              "INNER JOIN objeto_perdido op ON op.ID_EST_OP = e.STATE_ID " +
                              "SET e.EST_GRL_STATE = ?, e.DAÑOS = ? " +
                              "WHERE op.ID_OP = ?";
        pstEstado = cn.prepareStatement(updateEstado);
        pstEstado.setString(1, estadoGrl);
        pstEstado.setString(2, danos);
        pstEstado.setInt(3, objetoPerdidoId);
        pstEstado.executeUpdate();

        String updateObjetoPerdido = "UPDATE objeto_perdido " +
                                     "SET NAME_OP = ?, IMG_OP_URL = ? " +
                                     "WHERE ID_OP = ?";
        pstObjetoPerdido = cn.prepareStatement(updateObjetoPerdido);
        pstObjetoPerdido.setString(1, nameOp);
        pstObjetoPerdido.setString(2, imgUrl);
        pstObjetoPerdido.setInt(3, objetoPerdidoId);
        pstObjetoPerdido.executeUpdate();

        // COMMIT
        cn.commit();
        System.out.println(pstDescripcion);
        System.out.println();
        System.out.println(pstUbicacion);
        System.out.println();
        System.out.println(pstEstado);
        System.out.println();
        System.out.println(pstObjetoPerdido);
        JOptionPane.showMessageDialog(null, "Datos actualizados correctamente.");

    } catch (Exception e) {
        try {
            if (cn != null) cn.rollback(); // De nuevo, para no papiar la base de datos
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al actualizar los datos.");
    } finally {
        try {
            if (pstDescripcion != null) pstDescripcion.close();
            if (pstUbicacion != null) pstUbicacion.close();
            if (pstEstado != null) pstEstado.close();
            if (pstObjetoPerdido != null) pstObjetoPerdido.close();
            if (cn != null) cn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

    
    private void enviar(){String color = colorField.getText();
String forma = formaField.getText();
String utilidad = utilidadField.getText();
String material = materialField.getText();
String tamano = tamañoField.getText();

//ubicacion
String ciudad = ciudadField.getText();
String calle = calleField.getText();
String colonia = coloniaField.getText();

// estado
String estadoGrl = estadoGrlField.getText();
String danos = dañosField.getText();

// objeto_perdido
String nameOp = nombreField.getText();
String imgUrl = imgUrlField.getText();
//RECUERDA EXPERIMENTAR::: int userId = Integer.parseInt(userField.getText());

Connection cn = null;
PreparedStatement pstDescripcion = null;
PreparedStatement pstUbicacion = null;
PreparedStatement pstEstado = null;
PreparedStatement pstObjetoPerdido = null;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    cn = DriverManager.getConnection("jdbc:mysql://localhost/cosasperdidas", "root", "");
    cn.setAutoCommit(false); //DTART TRANSACTION

    String queryDescripcion = "INSERT INTO descripcion (COLOR, FORMA, UTILIDAD, MATERIAL, TAMAÑO) VALUES (?, ?, ?, ?, ?)";
    pstDescripcion = cn.prepareStatement(queryDescripcion, PreparedStatement.RETURN_GENERATED_KEYS); //LAST_GENERATEDKEY
    pstDescripcion.setString(1, color);
    pstDescripcion.setString(2, forma);
    pstDescripcion.setString(3, utilidad);
    pstDescripcion.setString(4, material);
    pstDescripcion.setString(5, tamano);
    pstDescripcion.executeUpdate();
    ResultSet rsDesc = pstDescripcion.getGeneratedKeys();
    rsDesc.next();
    int lastDescId = rsDesc.getInt(1); 

   
    String queryUbicacion = "INSERT INTO ubicacion (CIUDAD, CALLE, COLONIA) VALUES (?, ?, ?)";
    pstUbicacion = cn.prepareStatement(queryUbicacion, PreparedStatement.RETURN_GENERATED_KEYS);
    pstUbicacion.setString(1, ciudad);
    pstUbicacion.setString(2, calle);
    pstUbicacion.setString(3, colonia);
    pstUbicacion.executeUpdate();
    ResultSet rsUbicacion = pstUbicacion.getGeneratedKeys();
    rsUbicacion.next();
    int lastUbicacionId = rsUbicacion.getInt(1); 

   
    String queryEstado = "INSERT INTO estado (EST_GRL_STATE, DAÑOS) VALUES (?, ?)";
    pstEstado = cn.prepareStatement(queryEstado, PreparedStatement.RETURN_GENERATED_KEYS);
    pstEstado.setString(1, estadoGrl);
    pstEstado.setString(2, danos);
    pstEstado.executeUpdate();
    ResultSet rsEstado = pstEstado.getGeneratedKeys();
    rsEstado.next();
    int lastEstadoId = rsEstado.getInt(1); // Obtener el ID generado

   
    String queryObjetoPerdido = "INSERT INTO objeto_perdido (NAME_OP, ID_DESCRIPCION_OP, ID_EST_OP, ID_LUGAR_OP, IMG_OP_URL) VALUES (?, ?, ?, ?, ?)";
    pstObjetoPerdido = cn.prepareStatement(queryObjetoPerdido);
    pstObjetoPerdido.setString(1, nameOp);
    pstObjetoPerdido.setInt(2, lastDescId);
    pstObjetoPerdido.setInt(3, lastEstadoId);
    pstObjetoPerdido.setInt(4, lastUbicacionId);
    pstObjetoPerdido.setString(5, imgUrl);
    //pstObjetoPerdido.setInt(6, userId);
    pstObjetoPerdido.executeUpdate();

    
    cn.commit();//COMMIT
    JOptionPane.showMessageDialog(null, "Datos insertados correctamente.");

} catch (Exception e) {
    try {
        if (cn != null) cn.rollback(); //PARA NO PAPEAR LA BASE DE DATOS
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Error al insertar datos.");
} finally {
    try {
        if (pstDescripcion != null) pstDescripcion.close();
        if (pstUbicacion != null) pstUbicacion.close();
        if (pstEstado != null) pstEstado.close();
        if (pstObjetoPerdido != null) pstObjetoPerdido.close();
        if (cn != null) cn.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRAME_SQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRAME_SQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRAME_SQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRAME_SQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRAME_SQL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Colonia;
    private javax.swing.JLabel Colonia1;
    private javax.swing.JLabel Colonia2;
    private javax.swing.JLabel Colonia3;
    private javax.swing.JLabel Colonia4;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel Tamaño;
    private javax.swing.JTextField calleField;
    private javax.swing.JTextField ciudadField;
    private javax.swing.JTextField coloniaField;
    private javax.swing.JTextField colorField;
    private javax.swing.JTextField dañosField;
    private javax.swing.JTextField estadoGrlField;
    private javax.swing.JTextField formaField;
    private javax.swing.JTextField imgUrlField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField materialField;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField tamañoField;
    private javax.swing.JTextField utilidadField;
    // End of variables declaration//GEN-END:variables
}
